#!/usr/bin/env python3
"""Generate TypeScript types for the desktop renderer from the IPC contract.

    python3 nurse-manager/tools/gen_ipc_types.py           # rewrite the .d.ts
    python3 nurse-manager/tools/gen_ipc_types.py --check   # exit 1 if it is stale

The JSON Schema is the source of truth; the .d.ts is derived and committed
so the renderer builds without Python. Output is deterministic, so CI can
check that it has not drifted from the schema.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

IPC = Path(__file__).resolve().parents[1] / "contracts" / "ipc"
SCHEMA = IPC / "nurse-manager-ipc.schema.json"
COMMANDS = IPC / "commands.json"
OUTPUT = IPC / "nurse-manager-ipc.d.ts"

# The envelopes are emitted as generics keyed by command, not as flat types.
HAND_WRITTEN = {"OkEnvelope", "ErrorEnvelope"}


class UnsupportedSchema(ValueError):
    pass


def ts_type(schema, indent: str = "") -> str:
    if schema is True or schema == {}:
        return "unknown"
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(option, indent) for option in schema["anyOf"])
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(ts_type({"type": k}, indent) for k in kind)
    if kind in ("string",):
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        if schema.get("maxItems") == 0:
            return "readonly []"
        inner = ts_type(schema.get("items", True), indent)
        return f"ReadonlyArray<{inner}>" if "|" in inner else f"readonly {inner}[]"
    if kind == "object":
        if "properties" not in schema:
            return "Record<string, unknown>"
        return "{\n" + _members(schema, indent + "  ") + indent + "}"
    raise UnsupportedSchema(f"cannot express {schema!r} in TypeScript")


def _doc(schema, indent: str) -> str:
    notes = []
    if schema.get("description"):
        notes.append(schema["description"])
    if schema.get("pattern"):
        notes.append(f"@pattern {schema['pattern']}")
    for key in ("minimum", "maximum", "minItems", "maxItems"):
        if key in schema:
            notes.append(f"@{key} {schema[key]}")
    if not notes:
        return ""
    if len(notes) == 1:
        return f"{indent}/** {notes[0]} */\n"
    return indent + "/**\n" + "".join(f"{indent} * {n}\n" for n in notes) + indent + " */\n"


def _key(name: str) -> str:
    """A property name, quoted when it is not a plain identifier (``assistant-brief``)."""
    return name if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", name) else json.dumps(name)


def _members(schema, indent: str) -> str:
    required = set(schema.get("required", []))
    lines = []
    for name, sub in schema["properties"].items():
        optional = "" if name in required else "?"
        lines.append(_doc(sub, indent) + f"{indent}readonly {_key(name)}{optional}: {ts_type(sub, indent)};\n")
    return "".join(lines)


def generate() -> str:
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    commands = json.loads(COMMANDS.read_text(encoding="utf-8"))
    defs = schema["$defs"]
    missing = sorted(set(commands["commands"].values()) - set(defs))
    if missing:
        raise UnsupportedSchema(f"commands.json names undefined types: {missing}")
    out = [
        "// Generated by nurse-manager/tools/gen_ipc_types.py from",
        "// nurse-manager-ipc.schema.json and commands.json. Do not edit by hand.",
        "// Regenerate: python3 nurse-manager/tools/gen_ipc_types.py",
        "",
        f"/** {schema['title']}. */",
        "",
    ]
    for name in sorted(defs):
        if name in HAND_WRITTEN:
            continue
        sub = defs[name]
        doc = _doc(sub, "")
        if sub.get("type") == "object" and "properties" in sub:
            out.append(f"{doc}export interface {name} {{\n{_members(sub, '  ')}}}\n")
        else:
            out.append(f"{doc}export type {name} = {ts_type(sub)};\n")
    out.append("/** The data type each command returns inside an OkEnvelope. */")
    out.append("export interface CommandData {")
    for command, type_name in commands["commands"].items():
        out.append(f"  readonly {_key(command)}: {type_name};")
    out.append("}\n")
    out.append("export type Command = keyof CommandData;\n")
    out.append("export interface OkEnvelope<C extends Command = Command> {")
    out.append("  readonly contract: Contract;")
    out.append("  readonly command: C;")
    out.append("  readonly ok: true;")
    out.append("  readonly data: CommandData[C];")
    out.append("}\n")
    out.append("export interface ErrorEnvelope<C extends Command = Command> {")
    out.append("  readonly contract: Contract;")
    out.append("  readonly command: C;")
    out.append("  readonly ok: false;")
    out.append("  readonly error: IpcError;")
    out.append("}\n")
    out.append("/** Exactly one envelope is printed per command. Narrow on `ok`. */")
    out.append("export type Envelope<C extends Command = Command> = OkEnvelope<C> | ErrorEnvelope<C>;")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    text = generate()
    if argv == ["--check"]:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT} is stale; run tools/gen_ipc_types.py", file=sys.stderr)
            return 1
        return 0
    if argv:
        print(__doc__, file=sys.stderr)
        return 2
    OUTPUT.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
