# Copyright 2026 Robert Domondon
# SPDX-License-Identifier: Apache-2.0
"""Keep the browser's fixed choices in sync with the backend policy file."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
rules = json.loads((ROOT / "config" / "people-fields.json").read_text(encoding="utf-8"))
output = "// Generated by tools/gen_people_rules.py; edit config/people-fields.json.\n"
for name, key in (("PEOPLE_POLICY", "policy"), ("DATA_RULE", "data_rule"), ("PEOPLE_LABELS", "labels")):
    output += f"export const {name} = {json.dumps(rules[key], ensure_ascii=False)};\n"
path = ROOT / "renderer" / "people-rules.mjs"
if "--check" in sys.argv:
    if not path.exists() or path.read_text(encoding="utf-8") != output:
        raise SystemExit("generated people rules are stale")
else:
    path.write_text(output, encoding="utf-8")
