#!/usr/bin/env python3
"""Generate renderer/tokens.css from design/tokens.json.

    python3 nurse-manager/tools/gen_tokens_css.py           # rewrite tokens.css
    python3 nurse-manager/tools/gen_tokens_css.py --check   # exit 1 if stale

The contrast-tested token file is the only place colors are chosen; the
renderer uses the generated custom properties and never a raw hex value.
Night Studio follows the system dark-mode setting unless the manager picks
a theme, which the page records as data-theme on <html>.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS = ROOT / "design" / "tokens.json"
OUTPUT = ROOT / "renderer" / "tokens.css"


def _block(selector: str, theme: dict[str, str], indent: str = "") -> list[str]:
    lines = [f"{indent}{selector} {{"]
    lines += [f"{indent}  --nm-{name}: {value};" for name, value in theme.items()]
    lines.append(f"{indent}}}")
    return lines


def generate() -> str:
    tokens = json.loads(TOKENS.read_text(encoding="utf-8"))
    day, night = tokens["themes"]["day"], tokens["themes"]["night-studio"]
    unit = tokens["spacing"]["unit_px"]
    radius = tokens["radius"]
    body = tokens["typography"]["body"]
    out = [
        "/* Generated by nurse-manager/tools/gen_tokens_css.py from design/tokens.json.",
        "   Do not edit by hand. */",
        "",
        *_block(":root", {
            **day,
            **{f"space-{i}": f"{unit * i}px" for i in (1, 2, 3, 4, 6, 8)},
            "radius-card": f"{radius['card_px']}px",
            "radius-card-large": f"{radius['card_large_px']}px",
            "radius-badge": f"{radius['badge_px']}px",
            "font-size-body": f"{body['min_size_px'] / 16}rem",
            "line-height-body": str(body["line_height"]),
        }),
        "",
        *_block(':root[data-theme="night"]', night),
        "",
        "@media (prefers-color-scheme: dark) {",
        *_block(':root:not([data-theme="day"])', night, "  "),
        "}",
    ]
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    text = generate()
    if argv == ["--check"]:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != text:
            print(f"{OUTPUT} is stale; run tools/gen_tokens_css.py", file=sys.stderr)
            return 1
        return 0
    if argv:
        print(__doc__, file=sys.stderr)
        return 2
    OUTPUT.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
