// Generated by nurse-manager/tools/gen_ipc_types.py from
// nurse-manager-ipc.schema.json and commands.json. Do not edit by hand.
// Regenerate: python3 nurse-manager/tools/gen_ipc_types.py

/** Nurse Manager IPC contract, version 1. */

export interface AcceptedOutput {
  readonly id: RecordId;
  readonly title: string;
  readonly accepted_by: string;
  readonly accepted_at: IsoDateTime;
}

export interface AcceptedOutputsSection {
  readonly state: SectionState;
  /** @maxItems 5 */
  readonly items: readonly AcceptedOutput[];
  readonly empty_message: string;
}

/** A governed action. Draft ready, accepted, exported, and sent are distinct states. */
export interface Action {
  readonly id: RecordId;
  readonly origin: "human" | "assistant";
  readonly proposed_by: string;
  readonly effect: string;
  readonly purpose: string;
  readonly artifact_revision_id: RecordId | null;
  /** @pattern ^([0-9a-f]{64})?$ */
  readonly payload_sha256: string;
  readonly destination: string;
  /** @minimum 0 */
  readonly cost_limit_cents: number;
  readonly expected_effect: string;
  readonly tier: "green" | "yellow" | "red";
  readonly policy_decision: "allow" | "require_approval" | "deny";
  readonly policy_reasons: readonly string[];
  readonly status: "denied" | "awaiting_approval" | "approved" | "executing" | "succeeded" | "failed" | "effect_unknown" | "stale";
}

/** A request waiting for a model right now, or the recurring brief waiting for its time. */
export interface AssistantAtWork {
  /** The request's id, or brief-schedule. */
  readonly id: RecordId | "brief-schedule";
  readonly kind: "request" | "schedule";
  readonly title: string;
  readonly detail: string;
  /** When a request began; null for the schedule. */
  readonly since: IsoDateTime | null;
}

/** One gate that runs before anything is sent. */
export interface AssistantCheck {
  readonly gate: "data_rules" | "edena" | "budget";
  readonly passed: boolean;
  /** Written for the manager. */
  readonly detail: string;
}

/** The answer to asking for an AI draft of the weekly brief. The revision is always a draft; drafted_by_model says whether a model wrote it. */
export interface AssistantDraft {
  readonly outcome: AssistantOutcome;
  readonly drafted_by_model: boolean;
  /** Written for the manager. Empty only when a model drafted it. */
  readonly reason: string;
  readonly provider: AssistantProvider;
  readonly model: string;
  readonly request_id: RecordId;
  readonly revision: Revision;
}

/** What happened to one request. Every outcome except 'drafted' returns the draft composed from records. */
export type AssistantOutcome = "drafted" | "no_model" | "refused_data_rules" | "refused_policy" | "refused_budget" | "refused_stopped" | "provider_failed" | "output_refused" | "stopped";

/** Exactly what asking the model would send, and the gates' verdicts. Nothing is sent to produce it. With no model connected, system and prompt are empty and will_send is false. */
export interface AssistantPreview {
  readonly week_of: IsoDate;
  readonly provider: AssistantProvider;
  readonly model: string;
  readonly runs_on: string;
  /** The instructions sent to the model. */
  readonly system: string;
  /** The record text sent to the model. */
  readonly prompt: string;
  /** Send it back with assistant-brief; a change since the preview refuses the request. */
  readonly prompt_sha256: Sha256 | "";
  readonly checks: readonly AssistantCheck[];
  readonly will_send: boolean;
  /** Why nothing would be sent. Empty when will_send is true. */
  readonly reason: string;
}

/** The connected AI provider. 'none' is the default (ADR 0004). There is no cloud value until a cloud service is chosen. */
export type AssistantProvider = "none" | "local";

/** AI settings, usage so far, and the gates every provider passes. */
export interface AssistantStatus {
  readonly provider: AssistantProvider;
  readonly model: string;
  readonly endpoint: string;
  /** Where the text goes, said plainly. */
  readonly runs_on: string;
  /** @minimum 0 */
  readonly monthly_budget_cents: number;
  /** @minimum 0 */
  readonly daily_request_limit: number;
  /** @minimum 0 */
  readonly requests_today: number;
  /** @minimum 0 */
  readonly spent_this_month_cents: number;
  readonly cloud: {
    readonly available: boolean;
    readonly reason: string;
  };
  /** @minItems 1 */
  readonly gates: readonly string[];
}

/** Every assistant working or waiting to work, and the one switch that stops them all (step 5.3). Also the answer to assistants-stop and assistants-resume. */
export interface AssistantsSection {
  readonly state: SectionState;
  readonly items: readonly AssistantAtWork[];
  readonly empty_message: string;
  /** While true, nothing is sent to a model, running requests are abandoned and their replies discarded, and the recurring brief waits. */
  readonly stopped: boolean;
  /** Who last stopped or restarted assistants; empty if nobody has. */
  readonly changed_by: string;
  readonly changed_at: IsoDateTime | null;
}

export interface BackupResult {
  readonly backup: string;
}

export interface Board {
  readonly sample: boolean;
  /**
   * @minItems 5
   * @maxItems 5
   */
  readonly columns: readonly BoardColumn[];
}

export interface BoardCard {
  readonly id: RecordId;
  readonly title: string;
  readonly owner: string;
  readonly due_date: IsoDate | null;
  readonly project: string | null;
  readonly blocked: boolean;
  readonly blocked_reason: string;
  readonly paused: boolean;
}

export interface BoardColumn {
  readonly status: TaskStatus;
  readonly label: string;
  /** @minimum 0 */
  readonly count: number;
  readonly cards: readonly BoardCard[];
}

/** The one scheduled run for a week. Drafted: a draft is waiting for review. Skipped: the week already had a brief. Failed: retried up to three attempts in all. */
export interface BriefRun {
  readonly week_of: IsoDate;
  readonly status: "drafted" | "skipped" | "failed";
  /**
   * @minimum 1
   * @maximum 3
   */
  readonly attempts: number;
  readonly revision_id: RecordId | null;
  readonly reason: string;
  readonly next_attempt_at: IsoDateTime | null;
  readonly at: IsoDateTime;
}

/** What one check of the recurring brief did. */
export interface BriefRunResult {
  readonly outcome: "off" | "stopped" | "not_due" | "done" | "waiting" | "gave_up" | "drafted" | "skipped" | "failed";
  readonly week_of: IsoDate | null;
  readonly run: BriefRun | null;
}

/** The recurring weekly brief: a records-only draft prepared at the chosen local weekday and hour while the app runs on this computer. Off by default. */
export interface BriefSchedule {
  readonly enabled: boolean;
  /**
   * 0 is Monday.
   * @minimum 0
   * @maximum 6
   */
  readonly weekday: number;
  /**
   * @minimum 0
   * @maximum 23
   */
  readonly hour: number;
  /** When the next draft is due, in local time; null when off. A past time means it runs within a minute. */
  readonly next_at: IsoDateTime | null;
  readonly last_run: BriefRun | null;
  /** The manager has stopped assistants: nothing is prepared until they let them work again. */
  readonly stopped: boolean;
}

/** Exactly what asking JEV about one proposed action would send. Nothing is sent to produce it. */
export interface ClassifierActionPreview {
  readonly action_id: RecordId;
  readonly job: "action_review";
  readonly provider: ClassifierProvider;
  readonly model: string;
  readonly runs_on: string;
  readonly request: string;
  readonly request_sha256: Sha256 | "";
  readonly checks: readonly AssistantCheck[];
  readonly will_send: boolean;
  readonly reason: string;
}

/** JEV's suggestion beside the policy's decision on one action. A hold must be acknowledged before approval; the policy's decision never changes. */
export interface ClassifierActionResult {
  readonly action_id: RecordId;
  readonly outcome: ClassifierOutcome | "acknowledged";
  /** Written for the manager. */
  readonly reason: string;
  readonly request_id: RecordId | "";
  readonly model: string;
  /** The policy's decision, as the option it corresponds to. */
  readonly core_decision: ClassifierOption;
  readonly suggestion: ClassifierOption | "";
  readonly probabilities: {
    /**
     * @minimum 0
     * @maximum 1
     */
    readonly allow?: number;
    /**
     * @minimum 0
     * @maximum 1
     */
    readonly require_human?: number;
    /**
     * @minimum 0
     * @maximum 1
     */
    readonly deny?: number;
  };
  readonly confidence: number | null;
  readonly hold: boolean;
  readonly acknowledged: boolean;
}

export type ClassifierJob = "action_review" | "refusal_check" | "routing" | "attention";

/** Which of JEV's jobs are on. All are off by default, and none can be on while JEV is not connected. */
export interface ClassifierJobs {
  readonly action_review: boolean;
  readonly refusal_check: boolean;
  readonly routing: boolean;
  readonly attention: boolean;
}

export type ClassifierOption = "allow" | "require_human" | "deny";

/** A suggested order for Needs my judgment. Every item is kept; no score is given. When JEV is unsure or unavailable, the usual order is returned. */
export interface ClassifierOrder {
  readonly outcome: ClassifierOutcome | "nothing_to_order" | "too_many";
  readonly reason: string;
  readonly request_id: RecordId | "";
  readonly model: string;
  readonly order: readonly RecordId[];
  readonly reordered: boolean;
}

/** What happened to one JEV request. Only 'answered' carries JEV's answer; every other outcome leaves things as they are without JEV. */
export type ClassifierOutcome = "answered" | "not_connected" | "job_off" | "refused_data_rules" | "refused_policy" | "refused_budget" | "refused_stopped" | "provider_failed" | "output_refused" | "stopped";

/** Exactly what asking JEV would send, and the gates' verdicts. Nothing is sent to produce it. When JEV is off or the job is off, request is empty and will_send is false. */
export interface ClassifierPreview {
  readonly job: ClassifierJob;
  readonly provider: ClassifierProvider;
  readonly model: string;
  readonly runs_on: string;
  /** The exact JSON body JEV would receive. */
  readonly request: string;
  /** Send it back with the request; a change since the preview refuses it. */
  readonly request_sha256: Sha256 | "";
  readonly checks: readonly AssistantCheck[];
  readonly will_send: boolean;
  /** Why nothing would be sent. Empty when will_send is true. */
  readonly reason: string;
}

/** JEV, or nothing. 'none' is the default (ADR 0006). */
export type ClassifierProvider = "none" | "jev";

/** A refusal category JEV found in a question, and the nearest permitted path. */
export interface ClassifierRefusal {
  readonly category: "patient_information" | "staff_performance" | "employer_confidential" | "clinical_decision" | "named_person_judgment";
  readonly label: string;
  readonly nearest_path: string;
}

/** Where JEV suggests a request belongs. A suggestion only: the manager chooses, and nothing starts. */
export interface ClassifierRoute {
  readonly outcome: ClassifierOutcome;
  readonly reason: string;
  readonly request_id: RecordId | "";
  readonly model: string;
  /** The request as asked, whitespace normalized. Never stored. */
  readonly request: string;
  /** Empty when JEV was not sure or did not answer. */
  readonly suggested: ClassifierRouteKey | "";
  readonly label: string;
  readonly confidence: number | null;
  /** @minItems 1 */
  readonly alternatives: readonly {
    readonly route: ClassifierRouteKey;
    readonly label: string;
  }[];
}

export type ClassifierRouteKey = "weekly_brief" | "project_question" | "pack_education" | "pack_committee" | "pack_communication" | "library" | "learning" | "contributions" | "memory" | "outside";

/** JEV settings, usage, what it does and never does, the gates every request passes, and TypeSafe's terms as read. Never the key. */
export interface ClassifierStatus {
  readonly provider: ClassifierProvider;
  /** The pinned model, e.g. jev-1.13.0; empty when not connected. */
  readonly model: string;
  readonly jobs: ClassifierJobs;
  /**
   * @minimum 0
   * @maximum 2000
   */
  readonly daily_request_limit: number;
  /** Where the text goes, said plainly. */
  readonly runs_on: string;
  /** Where the key is kept: the operating system's credential store. */
  readonly keystore: string;
  readonly keystore_available: boolean;
  /** @minimum 0 */
  readonly requests_today: number;
  /** @minimum 0 */
  readonly input_tokens_this_month: number;
  /** @minItems 1 */
  readonly what_it_does: readonly string[];
  /** @minItems 1 */
  readonly never_does: readonly string[];
  /** @minItems 1 */
  readonly gates: readonly string[];
  /** @minItems 1 */
  readonly terms: readonly string[];
}

export type Contract = "nurse-manager-ipc@1";

/** One of the manager's contributions and who shares the credit. Verified means the manager wrote the evidence that shows it happened. */
export interface ContributionItem {
  readonly id: RecordId;
  readonly title: string;
  readonly kind: "improvement" | "teaching" | "committee" | "presentation" | "publication";
  readonly occurred_on: IsoDate;
  readonly my_part: string;
  /** Teams, groups or roles; never a ranking of named colleagues. */
  readonly shared_credit: string;
  readonly project_id: RecordId | null;
  readonly project_title: string | null;
  readonly status: "draft" | "verified";
  readonly evidence: string;
  readonly verified_on: IsoDate | null;
}

export interface ContributionResult {
  readonly item: ContributionItem;
}

/** Contributions: drafts awaiting evidence, then verified, newest first. Stated facts, never a score or a ranking. */
export interface Contributions {
  readonly sample: boolean;
  readonly today: IsoDate;
  readonly items: readonly ContributionItem[];
  /** @minimum 0 */
  readonly drafts: number;
  /** @minimum 0 */
  readonly verified: number;
  /**
   * Verified contributions that happened in the calendar year of today, whenever they were verified.
   * @minimum 0
   */
  readonly this_year_verified: number;
  /** Projects a new contribution can be linked to. */
  readonly projects: readonly {
    readonly id: RecordId;
    readonly title: string;
  }[];
}

export interface Decision {
  readonly id: RecordId;
  readonly question: string;
  readonly decision: string;
  readonly decided_by: string;
  readonly decided_on: IsoDate;
  readonly rationale: string;
}

export interface EvidenceItem {
  readonly task_id: RecordId;
  readonly task: string;
  readonly evidence: string;
}

/** Feedback about a project's work, from a group or role. Never about a named person or anyone's performance. Addressed means a response was written. */
export interface Feedback {
  readonly id: RecordId;
  readonly from_group: string;
  readonly kind: "worked" | "change" | "question";
  readonly summary: string;
  readonly received_on: IsoDate;
  readonly status: "open" | "addressed";
  readonly response: string;
  readonly addressed_on: IsoDate | null;
}

export interface FeedbackResult {
  readonly feedback: Feedback;
}

export interface FollowUp {
  readonly id: RecordId;
  readonly title: string;
  readonly owner: string;
  readonly due_date: IsoDate;
  readonly overdue: boolean;
}

export interface FollowUpsSection {
  readonly state: SectionState;
  readonly items: readonly FollowUp[];
  readonly empty_message: string;
}

/** A truthful failure. The message is written for the manager; type names the error class. */
export interface IpcError {
  readonly type: string;
  readonly message: string;
}

/** @pattern ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ */
export type IsoDate = string;

/** @pattern ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}([+-][0-9]{2}:[0-9]{2}|Z)$ */
export type IsoDateTime = string;

export interface JudgmentItem {
  readonly kind: "task" | "draft" | "action";
  readonly id: RecordId;
  readonly title: string;
  /** Present for tasks only. */
  readonly owner?: string;
}

export interface JudgmentSection {
  readonly state: SectionState;
  readonly items: readonly JudgmentItem[];
  readonly empty_message: string;
}

/** Learning and Growth: in progress, planned, then completed. Stated facts, never a score. */
export interface Learning {
  readonly sample: boolean;
  readonly today: IsoDate;
  readonly items: readonly LearningItem[];
  /** @minimum 0 */
  readonly in_progress: number;
  /** @minimum 0 */
  readonly planned: number;
  /** @minimum 0 */
  readonly completed_this_year: number;
  /** @minimum 0 */
  readonly hours_this_year: number;
  /**
   * Not completed and past its target date.
   * @minimum 0
   */
  readonly past_target: number;
}

/** One piece of the manager's own professional learning. Completed means a takeaway and a date were written. */
export interface LearningItem {
  readonly id: RecordId;
  readonly title: string;
  readonly kind: "course" | "reading" | "conference" | "certification" | "mentoring";
  readonly status: "planned" | "in_progress" | "completed";
  readonly target_date: IsoDate | null;
  /**
   * @minimum 0
   * @maximum 500
   */
  readonly hours: number | null;
  readonly takeaway: string;
  readonly completed_on: IsoDate | null;
}

export interface LearningResult {
  readonly item: LearningItem;
}

/** Every source in the workspace, overdue reviews first. */
export interface Library {
  readonly sample: boolean;
  readonly today: IsoDate;
  readonly items: readonly LibraryItem[];
  /** @minimum 0 */
  readonly review_overdue: number;
  /** Projects a new source can belong to. */
  readonly projects: readonly {
    readonly id: RecordId;
    readonly title: string;
  }[];
}

/** One source in the workspace. The reference is shown as text, never opened by the app. */
export interface LibraryItem {
  readonly id: RecordId;
  readonly title: string;
  readonly kind: "public" | "synthetic" | "personal_permitted";
  readonly reference: string;
  readonly data_class: "D0" | "D1";
  readonly project_id: RecordId | null;
  readonly project: string | null;
  readonly review_date: IsoDate | null;
  readonly review_overdue: boolean;
}

/** Scoped memory: in use first, then expired, then excluded. Only memories in use are ever sent, and only to Think with this project. */
export interface Memory {
  readonly sample: boolean;
  readonly today: IsoDate;
  readonly items: readonly MemoryItem[];
  /** @minimum 0 */
  readonly in_use: number;
  /** @minimum 0 */
  readonly excluded: number;
  /** @minimum 0 */
  readonly expired: number;
  /** Projects a new memory can be scoped to. */
  readonly projects: readonly {
    readonly id: RecordId;
    readonly title: string;
  }[];
}

/** The memory is gone; only its id remains, in the audit log. */
export interface MemoryDeleted {
  readonly deleted: RecordId;
}

/** One thing the manager asked the assistant to remember, in their own words. Excluded or expired memories are kept but never sent. */
export interface MemoryItem {
  readonly id: RecordId;
  readonly content: string;
  /** Null means all work. */
  readonly project_id: RecordId | null;
  readonly project_title: string | null;
  readonly status: "active" | "excluded";
  /** Who wrote or last corrected it, and when. */
  readonly provenance: string;
  readonly expires_on: IsoDate | null;
  readonly expired: boolean;
}

export interface MemoryResult {
  readonly item: MemoryItem;
}

/** What needs my attention? Every section reads the same records as the board and table. */
export interface MissionControl {
  readonly workspace: string;
  readonly sample: boolean;
  readonly today: IsoDate;
  readonly week_of: IsoDate;
  readonly priorities: PrioritiesSection;
  readonly needs_my_judgment: JudgmentSection;
  readonly projects_in_motion: ProjectsSection;
  readonly follow_ups: FollowUpsSection;
  readonly assistants_at_work: AssistantsSection;
  readonly recent_accepted_outputs: AcceptedOutputsSection;
  readonly task_counts: TaskCounts;
}

/** A reviewed, versioned set of templates with its maintainer and review dates. Only a current pack can start a document; one past its review date, or failing its checks, says why. */
export interface Pack {
  readonly id: string;
  readonly title: string;
  readonly version: string;
  readonly purpose: string;
  readonly maintainer: string;
  readonly reviewed_on: IsoDate | null;
  readonly review_by: IsoDate | null;
  readonly status: "current" | "due_for_review" | "unavailable";
  /** Why it cannot start a document; empty when current. */
  readonly reason: string;
  readonly rules: readonly string[];
  readonly templates: readonly PackTemplate[];
}

/** A document started from a pack: which pack version and template, and where its latest revision stands. */
export interface PackDocument {
  readonly id: RecordId;
  readonly title: string;
  readonly project_id: RecordId | null;
  readonly project_title: string | null;
  readonly pack_id: string;
  readonly pack_version: string;
  readonly template_id: string;
  /** @minimum 1 */
  readonly revision_no: number;
  /** Of the latest revision. */
  readonly status: "draft" | "accepted";
  /** Some revision is accepted, even if a newer draft exists. */
  readonly has_accepted: boolean;
  readonly updated_at: IsoDateTime;
}

/** One pack document: the latest revision (rendered with its banner, and its raw text to edit) and the accepted one. Accept it with the accept command. */
export interface PackDocumentView {
  readonly sample: boolean;
  readonly document: PackDocument;
  readonly current: {
    readonly revision: Revision;
    /** The only rendering; it always carries its status banner. */
    readonly markdown: string;
    /** The text to edit; send its revision sha256 back as the base. */
    readonly body_markdown: string;
  };
  readonly accepted: Revision | null;
}

/** One template a pack uses, from the shared deliverable catalog. */
export interface PackTemplate {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  readonly sections: readonly string[];
}

/** Education, committee, and communication packs, and the documents started from them. */
export interface Packs {
  readonly sample: boolean;
  readonly today: IsoDate;
  readonly packs: readonly Pack[];
  readonly documents: readonly PackDocument[];
  /** Projects a new document can be for. */
  readonly projects: readonly {
    readonly id: RecordId;
    readonly title: string;
  }[];
}

export interface PilotChoice {
  readonly value: string;
  readonly label: string;
}

/** The manager's pilot feedback, newest first. Nothing here is sent anywhere; an export is text the manager saves and shares themselves. */
export interface PilotFeedback {
  readonly sample: boolean;
  readonly items: readonly PilotFeedbackItem[];
  /** @minimum 0 */
  readonly not_yet_exported: number;
  readonly last_export: {
    /** @minimum 1 */
    readonly items: number;
    readonly exported_at: IsoDateTime;
  } | null;
  readonly areas: readonly PilotChoice[];
  readonly kinds: readonly PilotChoice[];
}

/** The feedback is gone; only its id remains, in the audit log. */
export interface PilotFeedbackDeleted {
  readonly deleted: RecordId;
}

/** The export the manager reviewed: the same text and hash as the preview. The manager saves it and decides who receives it. */
export interface PilotFeedbackExport {
  readonly id: RecordId;
  readonly exported_at: IsoDateTime;
  readonly text: string;
  readonly sha256: Sha256;
  /** @minimum 1 */
  readonly items: number;
  /** @pattern ^nurse-ai-os-pilot-feedback-[0-9]{4}-[0-9]{2}-[0-9]{2}\.md$ */
  readonly filename: string;
  readonly can_export: true;
  readonly reason: "";
  /** @maxItems 0 */
  readonly findings: readonly [];
}

/** One piece of pilot feedback about the app itself, kept on this computer. */
export interface PilotFeedbackItem {
  readonly id: RecordId;
  readonly area: "getting_started" | "mission_control" | "weekly_brief" | "projects" | "ai_assistance" | "packs" | "other";
  readonly kind: "worked" | "problem" | "idea" | "question";
  readonly summary: string;
  readonly created_at: IsoDateTime;
  /** When it was last in an export the manager made; null if never. */
  readonly exported_at: IsoDateTime | null;
}

/** Exactly the text an export would hold, and whether the privacy screen lets it be made. Nothing is exported or sent. Findings are entity types only, never the matched text. */
export interface PilotFeedbackPreview {
  readonly text: string;
  readonly sha256: Sha256;
  /** @minimum 0 */
  readonly items: number;
  /** @pattern ^nurse-ai-os-pilot-feedback-[0-9]{4}-[0-9]{2}-[0-9]{2}\.md$ */
  readonly filename: string;
  readonly can_export: boolean;
  /** Why it cannot be exported; empty when it can. */
  readonly reason: string;
  readonly findings: readonly string[];
}

export interface PilotFeedbackResult {
  readonly item: PilotFeedbackItem;
}

export interface PrioritiesSection {
  readonly state: SectionState;
  /** @maxItems 3 */
  readonly items: readonly Priority[];
  readonly empty_message: string;
}

export interface Priority {
  /**
   * @minimum 1
   * @maximum 3
   */
  readonly rank: number;
  readonly text: string;
  readonly project_id: RecordId | null;
}

/** The answer to a question about one project. It is a suggestion shown to the manager and is never saved; the ledger keeps only metadata. */
export interface ProjectAnswer {
  /** refused_intake: JEV's refusal check stopped the question before the model saw it; request_id is then JEV's request. */
  readonly outcome: "answered" | "no_model" | "refused_data_rules" | "refused_policy" | "refused_budget" | "refused_stopped" | "provider_failed" | "output_refused" | "stopped" | "refused_intake";
  readonly answered_by_model: boolean;
  /** Written for the manager. Empty only when the model answered. */
  readonly reason: string;
  readonly provider: AssistantProvider;
  readonly model: string;
  readonly request_id: RecordId;
  readonly project_id: RecordId;
  /** The question as asked, whitespace normalized. Send it back with note-keep. */
  readonly question: string;
  /** Markdown with record citations; empty unless the model answered. */
  readonly answer: string;
  readonly source_refs: readonly RecordId[];
  /** Why JEV refused the question, and the nearest permitted path; null unless outcome is refused_intake. */
  readonly refusal: null | ClassifierRefusal;
}

/** What will move this initiative forward? Tasks use the same rows and ids as the table. */
export interface ProjectDashboard {
  readonly sample: boolean;
  readonly today: IsoDate;
  readonly project: ProjectSummaryHeader;
  readonly readiness: Readiness;
  readonly tasks: readonly TableRow[];
  readonly decisions: readonly Decision[];
  readonly resources: readonly Resource[];
  readonly evidence: readonly EvidenceItem[];
  /** Open feedback first, then addressed; newest first within each. */
  readonly feedback: readonly Feedback[];
  /** AI answers the manager chose to keep, newest first. */
  readonly notes: readonly ProjectNote[];
}

/** An AI answer the manager kept. Its text is exactly what the model answered (proven by the hash the request ledger recorded), and keeping it was the manager's acceptance. */
export interface ProjectNote {
  readonly id: RecordId;
  readonly project_id: RecordId;
  readonly request_id: RecordId;
  readonly question: string;
  readonly body_markdown: string;
  readonly sha256: Sha256;
  readonly source_refs: readonly RecordId[];
  /** assistant:<provider> */
  readonly written_by: string;
  readonly model: string;
  readonly kept_by: string;
  readonly kept_at: IsoDateTime;
}

/** Exactly what asking the model about one project would send, and the gates' verdicts. Nothing is sent to produce it. With no model connected, system and prompt are empty and will_send is false. */
export interface ProjectQuestionPreview {
  readonly project_id: RecordId;
  readonly provider: AssistantProvider;
  readonly model: string;
  readonly runs_on: string;
  /** The instructions sent to the model. */
  readonly system: string;
  /** The question and the project's record text sent to the model. */
  readonly prompt: string;
  /** Send it back with assistant-project; a change since the preview refuses the request. */
  readonly prompt_sha256: Sha256 | "";
  readonly checks: readonly AssistantCheck[];
  readonly will_send: boolean;
  /** Why nothing would be sent. Empty when will_send is true. */
  readonly reason: string;
  /** JEV's refusal check on the question (ADR 0006): what it would be sent before the model sees the question. Send its request_sha256 back with assistant-project when will_send is true. */
  readonly classifier: ClassifierPreview;
}

export interface ProjectSummary {
  readonly id: RecordId;
  readonly title: string;
  readonly owner: string;
  readonly next_milestone: string;
  /** @minimum 0 */
  readonly open_tasks: number;
  /** @minimum 0 */
  readonly completed_tasks: number;
  /** @minimum 0 */
  readonly blocked_tasks: number;
}

export interface ProjectSummaryHeader {
  readonly id: RecordId;
  readonly title: string;
  readonly purpose: string;
  /** The accountable owner. */
  readonly owner: string;
  readonly next_milestone: string;
  readonly status: "active" | "paused" | "completed";
}

export interface ProjectsSection {
  readonly state: SectionState;
  readonly items: readonly ProjectSummary[];
  readonly empty_message: string;
}

/** Stated facts about readiness. Deliberately not a score or a percentage. */
export interface Readiness {
  readonly has_next_milestone: boolean;
  /** @minimum 0 */
  readonly open_tasks: number;
  /** @minimum 0 */
  readonly completed_tasks: number;
  /** @minimum 0 */
  readonly blocked_tasks: number;
  /** @minimum 0 */
  readonly needs_judgment: number;
  /** @minimum 0 */
  readonly overdue_tasks: number;
  /**
   * Ready or in-progress tasks with no next action written down.
   * @minimum 0
   */
  readonly tasks_without_next_action: number;
  /**
   * Feedback not yet addressed.
   * @minimum 0
   */
  readonly open_feedback: number;
}

export interface Receipt {
  readonly action_id: RecordId;
  readonly outcome: "succeeded" | "failed" | "effect_unknown";
  readonly detail: string;
  readonly recorded_at: IsoDateTime;
}

/** After a crash: every export that was interrupted, settled by checking the file on disk. Nothing is run again; an empty list means nothing was interrupted. */
export interface ReconcileResult {
  readonly settled: readonly Receipt[];
}

/** @pattern ^(ws|prj|tsk|dec|src|pri|art|rev|act|air|note|fbk|lrn|ctb|mem|plf|plx|clr)-[0-9a-f]{12}$ */
export type RecordId = string;

export interface Resource {
  readonly id: RecordId;
  readonly title: string;
  readonly kind: "public" | "synthetic" | "personal_permitted";
  readonly reference: string;
  readonly review_date: IsoDate | null;
  readonly review_overdue: boolean;
}

export interface RestoreResult {
  readonly restored_from: string;
  /** Always taken, so even an accepted discard is recoverable. */
  readonly pre_restore_backup: string;
}

/** One revision of a brief. Accepted means a human accepted exactly this text (sha256). */
export interface Revision {
  readonly id: RecordId;
  readonly artifact_id: RecordId;
  /** @minimum 1 */
  readonly revision_no: number;
  readonly status: "draft" | "accepted" | "superseded";
  readonly sha256: Sha256;
  readonly source_refs: readonly RecordId[];
  /** Who wrote this text: the manager, or assistant:<provider> for a model's draft. */
  readonly created_by: string;
  readonly accepted_by: string | null;
  readonly accepted_at: IsoDateTime | null;
}

export interface SampleResult {
  readonly workspace: Workspace;
  readonly week_of: IsoDate;
  readonly today: IsoDate;
}

export type SectionState = "ok" | "empty";

/** @pattern ^[0-9a-f]{64}$ */
export type Sha256 = string;

export interface ShownRevision {
  readonly revision: Revision;
  /** The only rendering; it always carries its status banner. */
  readonly markdown: string;
}

export interface SourceResult {
  readonly source: LibraryItem;
}

export interface Table {
  readonly sample: boolean;
  readonly columns: ReadonlyArray<"task" | "project" | "owner" | "due_date" | "status" | "reviewer" | "evidence" | "next_action">;
  readonly rows: readonly TableRow[];
}

export interface TableRow {
  readonly id: RecordId;
  readonly task: string;
  readonly project: string | null;
  readonly owner: string;
  readonly due_date: IsoDate | null;
  readonly status: TaskStatus;
  readonly blocked: boolean;
  readonly paused: boolean;
  readonly reviewer: string;
  readonly evidence: string;
  readonly next_action: string;
}

export interface TaskCounts {
  /** @minimum 0 */
  readonly idea: number;
  /** @minimum 0 */
  readonly ready: number;
  /** @minimum 0 */
  readonly in_progress: number;
  /** @minimum 0 */
  readonly needs_judgment: number;
  /** @minimum 0 */
  readonly completed: number;
}

export type TaskStatus = "idea" | "ready" | "in_progress" | "needs_judgment" | "completed";

/** One download a signed feed names. Check the file against its sha256 before installing. */
export interface UpdateArtifact {
  /** @pattern ^[a-z0-9][a-z0-9-]{1,31}$ */
  readonly platform: string;
  /** @pattern ^https:// */
  readonly url: string;
  readonly sha256: Sha256;
}

/** The answer to checking for updates. Advisory only: nothing is downloaded or installed. not_configured means no update key is pinned, so no feed is trusted. */
export interface UpdateCheck {
  readonly current_version: string;
  readonly status: "not_configured" | "current" | "update_available";
  readonly reason: string;
  readonly latest: UpdateRelease | null;
  readonly sequence: number | null;
  readonly key_id: Sha256 | null;
}

/** A release newer than this one, from a feed whose signature verified. */
export interface UpdateRelease {
  /** @pattern ^[0-9]+\.[0-9]+\.[0-9]+$ */
  readonly version: string;
  /** The workspace schema it upgrades to; empty if the feed does not say. */
  readonly schema: string;
  readonly notes: string;
  /** @minItems 1 */
  readonly artifacts: readonly UpdateArtifact[];
}

/** One week's brief: the newest revision, rendered with its status banner, and the accepted revision if there is one. */
export interface WeeklyBrief {
  readonly week_of: IsoDate;
  readonly current: ShownRevision | null;
  readonly accepted: Revision | null;
  readonly schedule: BriefSchedule;
}

export interface Workspace {
  readonly id: RecordId;
  readonly name: string;
  readonly owner: string;
  readonly profile: "personal_manager";
  /** True for the synthetic sample workspace; every view must say so. */
  readonly sample: boolean;
}

/** The data type each command returns inside an OkEnvelope. */
export interface CommandData {
  readonly sample: SampleResult;
  readonly init: Workspace;
  readonly mission: MissionControl;
  readonly project: ProjectDashboard;
  readonly board: Board;
  readonly table: Table;
  readonly brief: Revision;
  readonly show: ShownRevision;
  readonly accept: Revision;
  readonly export: Action;
  readonly approve: Action;
  readonly run: Receipt;
  readonly backup: BackupResult;
  readonly restore: RestoreResult;
  readonly "update-check": UpdateCheck;
  readonly assistant: AssistantStatus;
  readonly "assistant-local": AssistantStatus;
  readonly "assistant-off": AssistantStatus;
  readonly "assistants-stop": AssistantsSection;
  readonly "assistants-resume": AssistantsSection;
  readonly "assistant-brief": AssistantDraft;
  readonly weekly: WeeklyBrief;
  readonly "assistant-preview": AssistantPreview;
  readonly "assistant-project-preview": ProjectQuestionPreview;
  readonly "assistant-project": ProjectAnswer;
  readonly "note-keep": ProjectNote;
  readonly "feedback-add": FeedbackResult;
  readonly "feedback-address": FeedbackResult;
  readonly library: Library;
  readonly "source-add": SourceResult;
  readonly learning: Learning;
  readonly "learning-add": LearningResult;
  readonly "learning-start": LearningResult;
  readonly "learning-complete": LearningResult;
  readonly contributions: Contributions;
  readonly "contribution-add": ContributionResult;
  readonly "contribution-verify": ContributionResult;
  readonly "brief-schedule-set": BriefSchedule;
  readonly "brief-run-due": BriefRunResult;
  readonly memory: Memory;
  readonly packs: Packs;
  readonly "pack-start": PackDocumentView;
  readonly document: PackDocumentView;
  readonly "document-save": PackDocumentView;
  readonly "memory-add": MemoryResult;
  readonly "memory-correct": MemoryResult;
  readonly "memory-exclude": MemoryResult;
  readonly "memory-include": MemoryResult;
  readonly "memory-delete": MemoryDeleted;
  readonly reconcile: ReconcileResult;
  readonly "pilot-feedback": PilotFeedback;
  readonly "pilot-feedback-add": PilotFeedbackResult;
  readonly "pilot-feedback-delete": PilotFeedbackDeleted;
  readonly "pilot-feedback-preview": PilotFeedbackPreview;
  readonly "pilot-feedback-export": PilotFeedbackExport;
  readonly classifier: ClassifierStatus;
  readonly "classifier-connect": ClassifierStatus;
  readonly "classifier-off": ClassifierStatus;
  readonly "classifier-jobs": ClassifierStatus;
  readonly "classifier-action-preview": ClassifierActionPreview;
  readonly "classifier-action": ClassifierActionResult;
  readonly "classifier-acknowledge": ClassifierActionResult;
  readonly "classifier-route-preview": ClassifierPreview;
  readonly "classifier-route": ClassifierRoute;
  readonly "classifier-order-preview": ClassifierPreview;
  readonly "classifier-order": ClassifierOrder;
}

export type Command = keyof CommandData;

export interface OkEnvelope<C extends Command = Command> {
  readonly contract: Contract;
  readonly command: C;
  readonly ok: true;
  readonly data: CommandData[C];
}

export interface ErrorEnvelope<C extends Command = Command> {
  readonly contract: Contract;
  readonly command: C;
  readonly ok: false;
  readonly error: IpcError;
}

/** Exactly one envelope is printed per command. Narrow on `ok`. */
export type Envelope<C extends Command = Command> = OkEnvelope<C> | ErrorEnvelope<C>;
