// Generated by nurse-manager/tools/gen_ipc_types.py from
// nurse-manager-ipc.schema.json and commands.json. Do not edit by hand.
// Regenerate: python3 nurse-manager/tools/gen_ipc_types.py

/** Nurse Manager IPC contract, version 1. */

export interface AcceptedOutput {
  readonly id: RecordId;
  readonly title: string;
  readonly accepted_by: string;
  readonly accepted_at: IsoDateTime;
}

export interface AcceptedOutputsSection {
  readonly state: SectionState;
  /** @maxItems 5 */
  readonly items: readonly AcceptedOutput[];
  readonly empty_message: string;
}

/** A governed action. Draft ready, accepted, exported, and sent are distinct states. */
export interface Action {
  readonly id: RecordId;
  readonly origin: "human" | "assistant";
  readonly proposed_by: string;
  readonly effect: string;
  readonly purpose: string;
  readonly artifact_revision_id: RecordId | null;
  /** @pattern ^([0-9a-f]{64})?$ */
  readonly payload_sha256: string;
  readonly destination: string;
  /** @minimum 0 */
  readonly cost_limit_cents: number;
  readonly expected_effect: string;
  readonly tier: "green" | "yellow" | "red";
  readonly policy_decision: "allow" | "require_approval" | "deny";
  readonly policy_reasons: readonly string[];
  readonly status: "denied" | "awaiting_approval" | "approved" | "executing" | "succeeded" | "failed" | "effect_unknown" | "stale";
}

/** The answer to asking for an AI draft of the weekly brief. The revision is always a draft; drafted_by_model says whether a model wrote it. */
export interface AssistantDraft {
  readonly outcome: AssistantOutcome;
  readonly drafted_by_model: boolean;
  /** Written for the manager. Empty only when a model drafted it. */
  readonly reason: string;
  readonly provider: AssistantProvider;
  readonly model: string;
  readonly request_id: RecordId;
  readonly revision: Revision;
}

/** What happened to one request. Every outcome except 'drafted' returns the draft composed from records. */
export type AssistantOutcome = "drafted" | "no_model" | "refused_data_rules" | "refused_policy" | "refused_budget" | "provider_failed" | "output_refused";

/** The connected AI provider. 'none' is the default (ADR 0004). There is no cloud value until a cloud service is chosen. */
export type AssistantProvider = "none" | "local";

/** AI settings, usage so far, and the gates every provider passes. */
export interface AssistantStatus {
  readonly provider: AssistantProvider;
  readonly model: string;
  readonly endpoint: string;
  /** Where the text goes, said plainly. */
  readonly runs_on: string;
  /** @minimum 0 */
  readonly monthly_budget_cents: number;
  /** @minimum 0 */
  readonly daily_request_limit: number;
  /** @minimum 0 */
  readonly requests_today: number;
  /** @minimum 0 */
  readonly spent_this_month_cents: number;
  readonly cloud: {
    readonly available: boolean;
    readonly reason: string;
  };
  /** @minItems 1 */
  readonly gates: readonly string[];
}

/** No assistant runtime exists yet; the section is honestly unavailable. */
export interface AssistantsSection {
  readonly state: "unavailable";
  /** @maxItems 0 */
  readonly items: readonly [];
  readonly empty_message: string;
}

export interface BackupResult {
  readonly backup: string;
}

export interface Board {
  readonly sample: boolean;
  /**
   * @minItems 5
   * @maxItems 5
   */
  readonly columns: readonly BoardColumn[];
}

export interface BoardCard {
  readonly id: RecordId;
  readonly title: string;
  readonly owner: string;
  readonly due_date: IsoDate | null;
  readonly project: string | null;
  readonly blocked: boolean;
  readonly blocked_reason: string;
  readonly paused: boolean;
}

export interface BoardColumn {
  readonly status: TaskStatus;
  readonly label: string;
  /** @minimum 0 */
  readonly count: number;
  readonly cards: readonly BoardCard[];
}

export type Contract = "nurse-manager-ipc@1";

export interface Decision {
  readonly id: RecordId;
  readonly question: string;
  readonly decision: string;
  readonly decided_by: string;
  readonly decided_on: IsoDate;
  readonly rationale: string;
}

export interface EvidenceItem {
  readonly task_id: RecordId;
  readonly task: string;
  readonly evidence: string;
}

export interface FollowUp {
  readonly id: RecordId;
  readonly title: string;
  readonly owner: string;
  readonly due_date: IsoDate;
  readonly overdue: boolean;
}

export interface FollowUpsSection {
  readonly state: SectionState;
  readonly items: readonly FollowUp[];
  readonly empty_message: string;
}

/** A truthful failure. The message is written for the manager; type names the error class. */
export interface IpcError {
  readonly type: string;
  readonly message: string;
}

/** @pattern ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ */
export type IsoDate = string;

/** @pattern ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}([+-][0-9]{2}:[0-9]{2}|Z)$ */
export type IsoDateTime = string;

export interface JudgmentItem {
  readonly kind: "task" | "draft" | "action";
  readonly id: RecordId;
  readonly title: string;
  /** Present for tasks only. */
  readonly owner?: string;
}

export interface JudgmentSection {
  readonly state: SectionState;
  readonly items: readonly JudgmentItem[];
  readonly empty_message: string;
}

/** What needs my attention? Every section reads the same records as the board and table. */
export interface MissionControl {
  readonly workspace: string;
  readonly sample: boolean;
  readonly today: IsoDate;
  readonly week_of: IsoDate;
  readonly priorities: PrioritiesSection;
  readonly needs_my_judgment: JudgmentSection;
  readonly projects_in_motion: ProjectsSection;
  readonly follow_ups: FollowUpsSection;
  readonly assistants_at_work: AssistantsSection;
  readonly recent_accepted_outputs: AcceptedOutputsSection;
  readonly task_counts: TaskCounts;
}

export interface PrioritiesSection {
  readonly state: SectionState;
  /** @maxItems 3 */
  readonly items: readonly Priority[];
  readonly empty_message: string;
}

export interface Priority {
  /**
   * @minimum 1
   * @maximum 3
   */
  readonly rank: number;
  readonly text: string;
  readonly project_id: RecordId | null;
}

/** What will move this initiative forward? Tasks use the same rows and ids as the table. */
export interface ProjectDashboard {
  readonly sample: boolean;
  readonly today: IsoDate;
  readonly project: ProjectSummaryHeader;
  readonly readiness: Readiness;
  readonly tasks: readonly TableRow[];
  readonly decisions: readonly Decision[];
  readonly resources: readonly Resource[];
  readonly evidence: readonly EvidenceItem[];
}

export interface ProjectSummary {
  readonly id: RecordId;
  readonly title: string;
  readonly owner: string;
  readonly next_milestone: string;
  /** @minimum 0 */
  readonly open_tasks: number;
  /** @minimum 0 */
  readonly completed_tasks: number;
  /** @minimum 0 */
  readonly blocked_tasks: number;
}

export interface ProjectSummaryHeader {
  readonly id: RecordId;
  readonly title: string;
  readonly purpose: string;
  /** The accountable owner. */
  readonly owner: string;
  readonly next_milestone: string;
  readonly status: "active" | "paused" | "completed";
}

export interface ProjectsSection {
  readonly state: SectionState;
  readonly items: readonly ProjectSummary[];
  readonly empty_message: string;
}

/** Stated facts about readiness. Deliberately not a score or a percentage. */
export interface Readiness {
  readonly has_next_milestone: boolean;
  /** @minimum 0 */
  readonly open_tasks: number;
  /** @minimum 0 */
  readonly completed_tasks: number;
  /** @minimum 0 */
  readonly blocked_tasks: number;
  /** @minimum 0 */
  readonly needs_judgment: number;
  /** @minimum 0 */
  readonly overdue_tasks: number;
  /**
   * Ready or in-progress tasks with no next action written down.
   * @minimum 0
   */
  readonly tasks_without_next_action: number;
}

export interface Receipt {
  readonly action_id: RecordId;
  readonly outcome: "succeeded" | "failed" | "effect_unknown";
  readonly detail: string;
  readonly recorded_at: IsoDateTime;
}

/** @pattern ^(ws|prj|tsk|dec|src|pri|art|rev|act|air)-[0-9a-f]{12}$ */
export type RecordId = string;

export interface Resource {
  readonly id: RecordId;
  readonly title: string;
  readonly kind: "public" | "synthetic" | "personal_permitted";
  readonly reference: string;
  readonly review_date: IsoDate | null;
  readonly review_overdue: boolean;
}

export interface RestoreResult {
  readonly restored_from: string;
  /** Always taken, so even an accepted discard is recoverable. */
  readonly pre_restore_backup: string;
}

/** One revision of a brief. Accepted means a human accepted exactly this text (sha256). */
export interface Revision {
  readonly id: RecordId;
  readonly artifact_id: RecordId;
  /** @minimum 1 */
  readonly revision_no: number;
  readonly status: "draft" | "accepted" | "superseded";
  readonly sha256: Sha256;
  readonly source_refs: readonly RecordId[];
  /** Who wrote this text: the manager, or assistant:<provider> for a model's draft. */
  readonly created_by: string;
  readonly accepted_by: string | null;
  readonly accepted_at: IsoDateTime | null;
}

export interface SampleResult {
  readonly workspace: Workspace;
  readonly week_of: IsoDate;
  readonly today: IsoDate;
}

export type SectionState = "ok" | "empty";

/** @pattern ^[0-9a-f]{64}$ */
export type Sha256 = string;

export interface ShownRevision {
  readonly revision: Revision;
  /** The only rendering; it always carries its status banner. */
  readonly markdown: string;
}

export interface Table {
  readonly sample: boolean;
  readonly columns: ReadonlyArray<"task" | "project" | "owner" | "due_date" | "status" | "reviewer" | "evidence" | "next_action">;
  readonly rows: readonly TableRow[];
}

export interface TableRow {
  readonly id: RecordId;
  readonly task: string;
  readonly project: string | null;
  readonly owner: string;
  readonly due_date: IsoDate | null;
  readonly status: TaskStatus;
  readonly blocked: boolean;
  readonly paused: boolean;
  readonly reviewer: string;
  readonly evidence: string;
  readonly next_action: string;
}

export interface TaskCounts {
  /** @minimum 0 */
  readonly idea: number;
  /** @minimum 0 */
  readonly ready: number;
  /** @minimum 0 */
  readonly in_progress: number;
  /** @minimum 0 */
  readonly needs_judgment: number;
  /** @minimum 0 */
  readonly completed: number;
}

export type TaskStatus = "idea" | "ready" | "in_progress" | "needs_judgment" | "completed";

export interface Workspace {
  readonly id: RecordId;
  readonly name: string;
  readonly owner: string;
  readonly profile: "personal_manager";
  /** True for the synthetic sample workspace; every view must say so. */
  readonly sample: boolean;
}

/** The data type each command returns inside an OkEnvelope. */
export interface CommandData {
  readonly sample: SampleResult;
  readonly init: Workspace;
  readonly mission: MissionControl;
  readonly project: ProjectDashboard;
  readonly board: Board;
  readonly table: Table;
  readonly brief: Revision;
  readonly show: ShownRevision;
  readonly accept: Revision;
  readonly export: Action;
  readonly approve: Action;
  readonly run: Receipt;
  readonly backup: BackupResult;
  readonly restore: RestoreResult;
  readonly assistant: AssistantStatus;
  readonly "assistant-local": AssistantStatus;
  readonly "assistant-off": AssistantStatus;
  readonly "assistant-brief": AssistantDraft;
}

export type Command = keyof CommandData;

export interface OkEnvelope<C extends Command = Command> {
  readonly contract: Contract;
  readonly command: C;
  readonly ok: true;
  readonly data: CommandData[C];
}

export interface ErrorEnvelope<C extends Command = Command> {
  readonly contract: Contract;
  readonly command: C;
  readonly ok: false;
  readonly error: IpcError;
}

/** Exactly one envelope is printed per command. Narrow on `ok`. */
export type Envelope<C extends Command = Command> = OkEnvelope<C> | ErrorEnvelope<C>;
