// Real local-app capture journey and deliberately interrupted replies.
import assert from 'node:assert/strict';
import { launchApp } from './app-launch.mjs';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { chromium } from 'playwright-core';
const work = mkdtempSync(join(tmpdir(), 'nm-capture-'));
let app = launchApp(work);
let browser;
try {
  const url = await app.ready;
  browser = await chromium.launch(process.env.CHROME_PATH ? { executablePath:process.env.CHROME_PATH,headless:true } : { channel:'chrome',headless:true });
  const context = await browser.newContext(); const page = await context.newPage();
  const errors=[]; page.on('pageerror', e => errors.push(e.message));
  await page.goto(url);
  await page.getByLabel('Workspace name').fill('Public planning');
  await page.getByRole('button',{name:'Create my workspace'}).click();
  await page.waitForSelector('.view--mission');
  await page.getByRole('link',{name:'Add work',exact:true}).focus(); await page.keyboard.press('Enter');
  await page.waitForSelector('.view--capture');
  assert.match(await page.locator('main').textContent(), /No projects yet.*No tasks yet.*No decisions recorded yet/s);
  const notice = text => page.waitForFunction(t => document.querySelector('.view--capture .notice')?.textContent?.includes(t),text);
  const save = async name => { await page.getByRole('button',{name,exact:true}).click(); await notice('Saved on this computer.'); };
  await page.getByLabel('Project title',{exact:true}).fill('Contact 555-867-5309');
  await page.getByLabel('Purpose',{exact:true}).fill('Public outline');
  await page.getByRole('button',{name:'Add project',exact:true}).click(); await notice('PHONE_NUMBER');
  assert.equal(await page.getByLabel('Project title',{exact:true}).inputValue(),'Contact 555-867-5309');
  await page.getByLabel('Project title',{exact:true}).fill('Outline practice');
  await page.getByLabel('Project owner role').selectOption('Manager');
  await save('Add project');
  assert.equal(await page.getByLabel('Project title',{exact:true}).inputValue(),'');
  const projectId = await page.locator('#capture-projects-heading').locator('..').locator('[data-record-id]').getAttribute('data-record-id');
  await page.getByLabel('Task title',{exact:true}).fill('Review outline');
  await page.getByLabel('Task project (optional)').selectOption(projectId);
  await page.getByLabel('Initial task status').selectOption('ready');
  await page.getByLabel('Task reviewer role (optional)').selectOption('Reviewer');
  await save('Add task');
  const taskId = await page.locator('#capture-tasks-heading').locator('..').locator('[data-record-id]').getAttribute('data-record-id');
  assert.equal(await page.getByLabel('Task to change').inputValue(),taskId);
  assert.equal(await page.getByLabel('Change',{exact:true}).inputValue(),'move');
  await page.getByLabel('Decision question').fill('Which outline?');
  await page.getByLabel('Decision made').fill('Short outline');
  await page.getByLabel('Decision maker role').selectOption('Council');
  await page.getByLabel('Decision project (optional)').selectOption(projectId);
  await save('Record decision');
  assert.match(await page.locator('#capture-decisions-heading').locator('..').textContent(), /Which outline.*Short outline.*Council/s);
  await page.getByLabel('Priority 1',{exact:true}).fill('Review public outline');
  await page.getByLabel('Priority 1 project (optional)').selectOption(projectId);
  await page.getByLabel('I reviewed the current list above').check();
  await save('Save priorities');
  await page.getByRole('link',{name:'Weekly brief',exact:true}).click(); await page.waitForSelector('.view--brief');
  await page.getByRole('button',{name:'Draft from my records',exact:true}).click();
  await page.waitForSelector('.brief-text');
  assert.match(await page.locator('.brief-text').textContent(),/Short outline/);
  assert.match(await page.locator('.brief-text').textContent(),/dec-[0-9a-f]{12}/);
  await page.getByRole('button',{name:/accept this version/}).click();
  await page.waitForFunction(() => /Version 1 is accepted/.test(document.activeElement?.textContent || ''));
  await page.getByRole('link',{name:'Table',exact:true}).click(); await page.waitForSelector('.view--table');
  assert.match(await page.locator(`[data-record-id="${taskId}"]`).textContent(),/Review outline/);
  await page.getByRole('link',{name:'Board',exact:true}).click(); await page.waitForSelector('.view--board');
  assert.match(await page.locator(`[data-record-id="${taskId}"]`).textContent(),/Review outline/);
  await page.goto(new URL(`#/project/${projectId}`,url).href); await page.waitForSelector('.view--project');
  assert.match(await page.locator('main').textContent(),/Short outline/);
  await page.getByRole('link',{name:'Add work',exact:true}).click(); await page.waitForSelector('.view--capture');
  await page.getByLabel('Target status (move or reopen)').selectOption('in_progress');
  await save('Save task change');
  await page.getByLabel('Change',{exact:true}).selectOption('block');
  await page.getByLabel('Reason (required').fill('Waiting for practice review');
  await save('Save task change');
  assert.match(await page.locator('#capture-tasks-heading').locator('..').textContent(),/blocked/);
  await page.getByLabel('Change',{exact:true}).selectOption('block');
  await page.getByLabel('Blocked value (set blocked)').selectOption('no'); await save('Save task change');
  await page.getByLabel('Change',{exact:true}).selectOption('pause'); await save('Save task change');
  assert.match(await page.locator('#capture-tasks-heading').locator('..').textContent(),/paused/);
  await page.getByLabel('Change',{exact:true}).selectOption('pause');
  await page.getByLabel('Paused value (set paused)').selectOption('no'); await save('Save task change');
  await page.getByLabel('Change',{exact:true}).selectOption('complete');
  await page.getByRole('button',{name:'Save task change'}).click(); await notice('evidence');
  await page.getByLabel('Evidence (required for completion)').fill('Public outline checked');
  await save('Save task change');
  assert.match(await page.locator('#capture-tasks-heading').locator('..').textContent(),/completed.*Public outline checked/s);
  await page.getByLabel('Change',{exact:true}).selectOption('reopen');
  await page.getByLabel('Reason (required').fill('Practice again'); await save('Save task change');
  assert.match(await page.locator('#capture-tasks-heading').locator('..').textContent(),/ready/);
  // Two tabs review the same list: the second cannot overwrite the first.
  const second = await context.newPage();
  const token = await page.evaluate(() => sessionStorage.getItem('nm-token'));
  await second.goto(new URL(`#token=${token}`,url).href); await second.waitForSelector('.view--mission');
  await second.getByRole('link',{name:'Add work',exact:true}).click(); await second.waitForSelector('.view--capture');
  await page.getByLabel('Priority 1',{exact:true}).fill('Newer public outline');
  await page.getByLabel('I reviewed the current list above').check(); await save('Save priorities');
  await second.getByLabel('Priority 1',{exact:true}).fill('Older tab proposal');
  await second.getByLabel('I reviewed the current list above').check();
  await second.getByRole('button',{name:'Save priorities',exact:true}).click();
  await second.waitForFunction(() => document.querySelector('.view--capture .notice')?.textContent?.includes('priorities changed'));
  assert.equal(await second.getByLabel('Priority 1',{exact:true}).inputValue(),'Older tab proposal');
  await second.getByRole('button',{name:'Refresh records'}).click();
  await second.waitForFunction(() => document.querySelector('[aria-label="Current priorities"]')?.textContent?.includes('Newer public outline'));
  assert.equal(await second.getByLabel('I reviewed the current list above').isChecked(),false);
  await page.getByLabel('Change',{exact:true}).selectOption('withdraw');
  await page.getByLabel('Reason (required').fill('Practice finished'); await save('Save task change');
  await second.getByLabel('Change',{exact:true}).selectOption('move');
  await second.getByRole('button',{name:'Save task change',exact:true}).click();
  await second.waitForFunction(() => /changed/.test(document.querySelector('.view--capture .notice')?.textContent || ''));
  assert.match(await page.locator('#capture-tasks-heading').locator('..').textContent(),/withdrawn/);
  // An unrelated successful save must not silently approve an edited old priority list.
  await page.getByLabel('Priority 1',{exact:true}).fill('Unsaved priority proposal');
  const originalHash = await page.locator('input[name="expected_sha256"]').inputValue();
  await second.getByRole('button',{name:'Refresh records'}).click();
  await second.waitForFunction(() => document.querySelector('.notice')?.textContent?.includes('Records refreshed'));
  await second.getByLabel('Priority 1',{exact:true}).fill('Concurrent priority replacement');
  await second.getByLabel('I reviewed the current list above').check();
  await second.getByRole('button',{name:'Save priorities',exact:true}).click();
  await second.waitForFunction(() => document.querySelector('.notice')?.textContent?.includes('Saved on this computer'));
  await page.getByLabel('Project title',{exact:true}).fill('Priority draft preservation');
  await page.getByLabel('Purpose',{exact:true}).fill('Public planning'); await save('Add project');
  assert.equal(await page.getByLabel('Priority 1',{exact:true}).inputValue(),'Unsaved priority proposal');
  assert.equal(await page.locator('input[name="expected_sha256"]').inputValue(),originalHash);
  await page.getByLabel('I reviewed the current list above').check();
  await page.getByRole('button',{name:'Save priorities',exact:true}).click(); await notice('priorities changed');
  // Forged option is refused in backend; unsaved text survives.
  await page.getByLabel('Project title',{exact:true}).fill('Custom role probe');
  await page.getByLabel('Purpose',{exact:true}).fill('Public practice');
  await page.getByLabel('Project owner role').evaluate(el => { el.add(new Option('Unapproved personal name','Unapproved personal name')); el.value='Unapproved personal name'; });
  await page.getByRole('button',{name:'Add project',exact:true}).click(); await notice('role');
  assert.equal(await page.getByLabel('Project title',{exact:true}).inputValue(),'Custom role probe');
  await page.getByLabel('Project owner role').selectOption('me');
  // Backend commits, response is lost. No retry, disabled until explicit refresh.
  await page.getByLabel('Project title',{exact:true}).fill('Lost reply practice');
  await page.route('**/ipc/project-add', async route => { await route.fetch(); await route.abort(); });
  await page.getByRole('button',{name:'Add project',exact:true}).click(); await notice('Save result unknown');
  assert.equal(await page.getByRole('button',{name:'Add project',exact:true}).isDisabled(),true);
  await page.unroute('**/ipc/project-add');
  await page.getByRole('link',{name:'Board',exact:true}).click(); await page.waitForSelector('.view--board');
  await page.getByRole('link',{name:'Add work',exact:true}).click(); await page.waitForSelector('.view--capture');
  assert.equal(await page.getByRole('button',{name:'Add project',exact:true}).isDisabled(),true);
  await page.getByRole('button',{name:'Refresh records'}).click(); await notice('Records refreshed');
  assert.equal(await page.getByRole('link',{name:'Lost reply practice',exact:true}).count(),1);
  assert.equal(await page.getByLabel('Project title',{exact:true}).inputValue(),'');
  // Success plus read failure: saved form clears; unrelated draft stays.
  await page.getByLabel('Project title',{exact:true}).fill('Refresh failure practice');
  await page.getByLabel('Purpose',{exact:true}).fill('Public planning');
  await page.getByLabel('Task title',{exact:true}).fill('Unsaved task draft');
  await page.route('**/ipc/capture?*', route => route.abort());
  await page.getByRole('button',{name:'Add project',exact:true}).click(); await notice('Saved on this computer. The records could not be refreshed');
  assert.equal(await page.getByLabel('Project title',{exact:true}).inputValue(),'');
  assert.equal(await page.getByLabel('Task title',{exact:true}).inputValue(),'Unsaved task draft');
  await page.unroute('**/ipc/capture?*');
  await page.getByRole('button',{name:'Refresh records'}).click(); await notice('Records refreshed');
  assert.equal(await page.getByRole('link',{name:'Refresh failure practice',exact:true}).count(),1);
  // Pending save, navigation away/back: prevent duplicate and recover controls.
  let release; const held = new Promise(resolve => { release=resolve; });
  let arrived; const arriving = new Promise(resolve => { arrived=resolve; });
  await page.route('**/ipc/project-add', async route => { arrived(); await held; await route.continue(); });
  await page.getByLabel('Project title',{exact:true}).fill('Slow save practice');
  await page.getByLabel('Purpose',{exact:true}).fill('Public planning');
  await page.getByRole('button',{name:'Add project',exact:true}).click(); await arriving;
  assert.equal(await page.getByRole('button',{name:'Add project',exact:true}).isDisabled(),true);
  await page.getByRole('link',{name:'Board',exact:true}).click(); await page.waitForSelector('.view--board');
  await page.getByRole('link',{name:'Add work',exact:true}).click(); await page.waitForSelector('.view--capture');
  assert.equal(await page.getByRole('button',{name:'Add project',exact:true}).isDisabled(),true);
  release(); await notice('earlier save succeeded');
  assert.equal(await page.getByRole('button',{name:'Refresh records'}).isDisabled(),false);
  await page.unroute('**/ipc/project-add');
  await page.getByRole('button',{name:'Refresh records'}).click(); await notice('Records refreshed');
  assert.equal(await page.getByRole('link',{name:'Slow save practice',exact:true}).count(),1);
  // Narrow view, theme and keyboard focus are usable.
  await page.setViewportSize({width:320,height:800});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
  await page.getByRole('button',{name:'Refresh records'}).focus(); await page.keyboard.press('Enter'); await notice('Records refreshed');
  assert.match(await page.evaluate(() => document.activeElement?.textContent || ''),/Records refreshed/);
  assert.deepEqual(errors,[]);
  await page.reload(); await page.waitForSelector('.view--capture');
  assert.equal(await page.getByRole('link',{name:'Slow save practice',exact:true}).count(),1);
  app.child.kill(); await app.exited;
  app = launchApp(work);
  const reopened = await context.newPage(); await reopened.goto(await app.ready);
  await reopened.waitForSelector('.view--mission');
  await reopened.getByRole('link',{name:'Add work',exact:true}).click(); await reopened.waitForSelector('.view--capture');
  assert.equal(await reopened.getByRole('link',{name:'Slow save practice',exact:true}).count(),1);
  assert.match(await reopened.locator('#capture-tasks-heading').locator('..').textContent(),/withdrawn/);
  assert.match(await reopened.locator('#capture-decisions-heading').locator('..').textContent(),/Short outline/);
  await context.close();
  console.log('Capture browser: shared records, task evidence/reopen, stale priorities, privacy/roles, lost reply, failed refresh, pending navigation, keyboard and narrow view passed.');
} finally {
  await browser?.close(); app.child.kill(); rmSync(work,{recursive:true,force:true});
}
