// Generated by tools/gen_people_rules.py; edit config/people-fields.json.
export const PEOPLE_POLICY = "personal-people@1";
export const DATA_RULE = "Use public or synthetic information and nonconfidential personal planning only. Do not enter patient details, names of other people, or confidential workplace information. Names are not automatically detected.";
export const PEOPLE_LABELS = ["me", "Manager", "Educator", "Council chair", "Unit coordinator", "Charge nurse", "Reviewer", "Review team", "Team", "Council", "Council members", "Quality council", "Unit Based Council members", "Committee", "Mentor", "Day shift", "Night shift", "Day shift huddle", "Night shift huddle"];
