#!/usr/bin/env python3
"""
NAIO OS — render-profile.py (Phase 3)

Renders a governed Hermes-ready profile bundle from naio-soul.json and optional
naio-projects.json. This is the first safe APPLY layer: it writes only to an
explicit --target directory, never directly to ~/.hermes.

Outputs:
  README-FIRST.md
  SOUL.md
  spheres/<sphere>.SOUL.md
  projects/<slug>.SYSTEM.md
  config/edena-runtime.yaml
  config/human-gates.yaml
  config/hermes-profile.patch.yaml
  logs/render-report.json
"""
import argparse, hashlib, json, re, shutil, sys, textwrap
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError as e:
    raise SystemExit("pyyaml is required for render-profile.py") from e

PHI_PATTERNS = [
    (re.compile(r"\b\d{3}-?\d{2}-?\d{4}\b"), "SSN-like pattern"),
    (re.compile(r"\b\d{3}[\s.-]?\d{3}[\s.-]?\d{4}\b", re.I), "phone-like pattern"),
    (re.compile(r"\b(?:MRN|medical record|patient id|DOB|date of birth|diagnosis|ICD-?10|CPT)\b[: ]", re.I), "clinical identifier"),
    (re.compile(r"\b(?:insurance|medicaid|medicare|policy)\s*(?:#|number|id)\b", re.I), "insurance identifier"),
]
ALLOWED_TIERS = {"green", "yellow"}
GATE_BY_TIER = {"green": "every-output", "yellow": "before-external-use"}
TOOLSETS_BY_TIER = {
    "green": ["file", "web", "search"],
    "yellow": ["file", "web", "search", "browser", "terminal"],
}

def refuse(msg: str) -> None:
    print(f"❌ REFUSED: {msg}", file=sys.stderr)
    sys.exit(2)

def load_json(path: Path) -> dict:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception as e:
        refuse(f"cannot read JSON {path}: {e}")
    if not isinstance(data, dict):
        refuse(f"{path} root must be a JSON object")
    return data

def screen_phi(label: str, data: dict) -> None:
    blob = json.dumps(data)
    hits = []
    for pat, name in PHI_PATTERNS:
        m = pat.search(blob)
        if m:
            hits.append(f"{name}: {m.group(0)[:24]!r}")
    if hits:
        refuse(f"PHI indicators detected in {label}: {'; '.join(hits)}")

def slugify(text: str) -> str:
    text = re.sub(r"[^a-zA-Z0-9]+", "-", text.strip().lower()).strip("-")
    return text or "project"

def safe_write(root: Path, rel: str, content: str) -> Path:
    path = (root / rel).resolve()
    if not str(path).startswith(str(root.resolve()) + "/") and path != root.resolve():
        refuse(f"unsafe render path escaped target: {rel}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path

def validate_soul(soul: dict) -> None:
    b = soul.get("boundaries", {})
    if b.get("no_phi_confirmed") is not True:
        refuse("SOUL boundary no_phi_confirmed must be true")
    if b.get("no_clinical_decisions_confirmed") is not True:
        refuse("SOUL boundary no_clinical_decisions_confirmed must be true")
    ceilings = soul.get("tier_ceilings", {})
    if not isinstance(ceilings, dict) or not ceilings:
        refuse("SOUL tier_ceilings must be present")
    bad = {k: v for k, v in ceilings.items() if v not in ALLOWED_TIERS}
    if bad:
        refuse(f"onboarding ceilings above yellow refused: {bad}")
    screen_phi("naio-soul.json", soul)

def validate_projects(projects: dict | None) -> None:
    if not projects:
        return
    plist = projects.get("projects", [])
    if projects.get("project_count") != len(plist):
        refuse("project_count mismatch in naio-projects.json")
    for p in plist:
        tier = p.get("edena_tier")
        if tier not in ALLOWED_TIERS:
            refuse(f"project tier above yellow refused: {p.get('name')}={tier}")
        rel = p.get("file_path", "")
        parts = Path(rel).parts
        if not rel.endswith(".md") or not parts or parts[0] != "04-Projects" or ".." in parts:
            refuse(f"unsafe project file_path refused: {rel}")
    screen_phi("naio-projects.json", projects)

def make_core_soul(soul: dict) -> str:
    ident = soul.get("identity", {})
    voice = soul.get("voice", {})
    vals = soul.get("values", [])
    b = soul.get("boundaries", {})
    values_text = "\n".join("- " + str(v) for v in vals) if vals else "- Dignity\n- Safety\n- Stewardship"
    return f"""# SOUL.md — Core Nurse AI OS Identity

Generated by NAIO OS Phase 3 renderer. Review before use.

## Identity
- Name: {ident.get('name', '(unset)')}
- Role: {ident.get('role_label', ident.get('role', '(unset)'))}
- One-liner: {ident.get('one_liner', '(unset)')}

## Values
{values_text}

## Voice
- Length: {voice.get('length', 'Concise and structured')}
- Formality: {voice.get('formality', 'Professional')}
- Pushback: {voice.get('pushback', 'Direct but kind')}
- Avoid: {voice.get('avoid', 'Hype, clinical overclaiming, PHI')}

## Hard boundaries
- No PHI: {b.get('no_phi_confirmed')}
- No clinical decisions: {b.get('no_clinical_decisions_confirmed')}
- Decisions always mine: {', '.join(b.get('decisions_always_mine', [])) or 'clinical/professional/external decisions'}
- Drafts allowed: {', '.join(b.get('drafts_without_asking', [])) or 'notes, outlines, checklists'}

## Doctrine
Agents propose. Humans judge. Nurses steward.

## Operating rule
Use this SOUL file as identity context only. Never infer patient facts, never request PHI,
and never convert AI output into clinical or external action without the required human gate.
"""

def make_sphere_soul(sphere: str, ceiling: str) -> str:
    gate = GATE_BY_TIER[ceiling]
    return f"""# {sphere.title()} SOUL — EDENA {ceiling.title()}

## Sphere ceiling
- EDENA tier ceiling: {ceiling}
- Required human gate: {gate}
- Allowed autonomy: agent may draft and organize; nurse remains final actor.

## Tool posture
- Suggested toolsets: {', '.join(TOOLSETS_BY_TIER[ceiling])}
- Permissions: least privilege, read-only by default, task-scoped.
- Irreversible actions: draft only; human executes.

## Safety boundary
No PHI. No patient-specific clinical decision support. No employer-confidential data unless explicitly sanitized.

Agents propose. Humans judge. Nurses steward.
"""

def make_project_prompt(p: dict) -> str:
    tier = p.get("edena_tier", "green")
    gate = p.get("human_gate") or GATE_BY_TIER[tier]
    return f"""# Project System Prompt — {p.get('suggested_prompt_name') or p.get('name')}

Sphere: {p.get('sphere_label', p.get('sphere'))}
EDENA tier: {tier}
Human gate: {gate}
Reversibility: {p.get('reversibility', 'reversible')}

## North star
Support the nurse with: {p.get('help', 'a bounded, non-PHI project')}.

## 90-day goal
{p.get('goal_90_days', 'Make progress safely without expanding scope or autonomy.')}

## Inputs allowed
Sanitized notes, agendas, public links, personal reflections, and non-PHI project context.

## Constraints
- No PHI, patient identifiers, clinical decisions, or employer-confidential details.
- Draft only; the nurse decides, sends, publishes, or acts.
- Do not exceed the sphere EDENA ceiling.
- State uncertainty and ask for missing non-sensitive context.

## Output format
Clear markdown with decisions needed, next actions, and any safety caveats.

## Gate
Before any external or irreversible use, pause and ask the nurse to review.

Agents propose. Humans judge. Nurses steward.
"""

def render_runtime(soul: dict, projects: dict | None) -> dict:
    ceilings = soul.get("tier_ceilings", {})
    spheres = soul.get("spheres", list(ceilings.keys()))
    runtime = {
        "version": "2.0.0-phase3",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "doctrine": "Agents propose. Humans judge. Nurses steward.",
        "mode": "generated-profile-bundle",
        "mutation_scope": "target-directory-only",
        "sphere_ceilings": {},
        "toolset_mapping": {},
        "human_gates": {},
        "permission_scoping": {
            "default": "read_only",
            "least_privilege": True,
            "complete_mediation": True,
            "irreversible_actions": "draft_then_human_executes",
        },
        "projects": [],
    }
    for sphere in spheres:
        tier = ceilings.get(sphere, "green")
        if tier not in ALLOWED_TIERS:
            refuse(f"invalid sphere tier after validation: {sphere}={tier}")
        runtime["sphere_ceilings"][sphere] = tier
        runtime["toolset_mapping"][sphere] = TOOLSETS_BY_TIER[tier]
        runtime["human_gates"][sphere] = GATE_BY_TIER[tier]
    for p in (projects or {}).get("projects", []):
        runtime["projects"].append({
            "name": p.get("name"),
            "sphere": p.get("sphere"),
            "tier": p.get("edena_tier"),
            "human_gate": p.get("human_gate"),
            "path": f"projects/{p.get('slug') or slugify(p.get('name','project'))}.SYSTEM.md",
        })
    return runtime

def main() -> int:
    ap = argparse.ArgumentParser(description="Render a governed Hermes-ready profile bundle.")
    ap.add_argument("--soul", required=True, help="path to naio-soul.json")
    ap.add_argument("--projects", default=None, help="path to naio-projects.json")
    ap.add_argument("--target", required=True, help="target output directory")
    ap.add_argument("--force", action="store_true", help="overwrite existing target")
    args = ap.parse_args()

    soul_path = Path(args.soul)
    if not soul_path.is_file():
        refuse(f"SOUL file not found: {soul_path}")
    soul = load_json(soul_path)
    projects = load_json(Path(args.projects)) if args.projects else None
    validate_soul(soul)
    validate_projects(projects)

    target = Path(args.target).expanduser().resolve()
    if target.exists():
        if not args.force:
            refuse(f"target already exists; pass --force to replace: {target}")
        if target == Path.home() or str(target) in ("/", str(Path.home() / ".hermes")):
            refuse("refusing to overwrite home or ~/.hermes directly")
        shutil.rmtree(target)
    target.mkdir(parents=True, exist_ok=True)

    written = []
    written.append(safe_write(target, "README-FIRST.md", textwrap.dedent(f"""
    # NAIO Hermes Profile Bundle — Phase 3

    This folder was generated from your SOUL Quiz and Life & Projects Quiz exports.

    **Nothing was written to ~/.hermes.** This is a governed, reviewable profile bundle.
    Copy/adapt it only after review.

    ## What is inside
    - `SOUL.md` — core identity and boundaries.
    - `spheres/` — per-sphere SOUL files with EDENA ceilings and gates.
    - `projects/` — project system prompts from Life & Projects.
    - `config/edena-runtime.yaml` — computed tier → gate/toolset mapping.
    - `config/human-gates.yaml` — gate behavior summary.
    - `config/hermes-profile.patch.yaml` — suggested Hermes config overlay, not auto-applied.

    ## Boundary
    No PHI. No clinical decisions. No irreversible external action without human review.

    Agents propose. Humans judge. Nurses steward.
    """).strip() + "\n"))
    written.append(safe_write(target, "SOUL.md", make_core_soul(soul)))

    for sphere, tier in soul.get("tier_ceilings", {}).items():
        written.append(safe_write(target, f"spheres/{sphere}.SOUL.md", make_sphere_soul(sphere, tier)))

    if projects:
        for p in projects.get("projects", []):
            slug = p.get("slug") or slugify(p.get("name", "project"))
            written.append(safe_write(target, f"projects/{slug}.SYSTEM.md", make_project_prompt(p)))

    runtime = render_runtime(soul, projects)
    written.append(safe_write(target, "config/edena-runtime.yaml", yaml.safe_dump(runtime, sort_keys=False, allow_unicode=True)))
    gates = {
        "version": "2.0.0-phase3",
        "non_removable_for": ["green", "yellow"],
        "gates": {
            "every-output": "Nurse reviews every generated output before use.",
            "before-external-use": "Nurse reviews before sending, publishing, sharing, or operational use.",
            "forced-irreversible": "Nurse executes irreversible actions manually; AI drafts only.",
        },
        "anti_rubber_stamp": "Reserve gates for meaning; show effect before asking for approval.",
    }
    written.append(safe_write(target, "config/human-gates.yaml", yaml.safe_dump(gates, sort_keys=False, allow_unicode=True)))
    patch = {
        "profile_name": "naio-generated-review-before-use",
        "soul_file": "SOUL.md",
        "project_context": ".hermes.md or selected project SYSTEM.md",
        "enabled_toolsets_by_sphere": runtime["toolset_mapping"],
        "human_gates": runtime["human_gates"],
        "note": "Suggested overlay only. Do not paste into ~/.hermes/config.yaml without review.",
    }
    written.append(safe_write(target, "config/hermes-profile.patch.yaml", yaml.safe_dump(patch, sort_keys=False, allow_unicode=True)))
    written.append(safe_write(target, ".hermes.md", "# NAIO Project Rules\n\nLoad SOUL.md first. Apply EDENA runtime gates. No PHI. No clinical decisions. Agents propose. Humans judge. Nurses steward.\n"))

    report = {
        "generated_at": runtime["generated_at"],
        "target": str(target),
        "files_written": [str(p.relative_to(target)) for p in written],
        "sha256": {str(p.relative_to(target)): hashlib.sha256(p.read_bytes()).hexdigest() for p in written},
    }
    written.append(safe_write(target, "logs/render-report.json", json.dumps(report, indent=2) + "\n"))
    print(f"✅ Phase 3 profile bundle rendered: {target}")
    print(f"   files_written={len(written)}")
    print("   mutation_scope=target-directory-only")
    return 0

if __name__ == "__main__":
    try:
        sys.exit(main())
    except SystemExit:
        raise
    except Exception as e:
        print(f"❌ INTERNAL ERROR: {e}", file=sys.stderr)
        sys.exit(1)
